### ISSUE TITLE
"Save" button in notification settings modal not working on desktop Safari

### ISSUE THREAD

**Issue by mgrzeca** [VernissageApp/VernissageWeb#118] opened 2024-10-06 12:05 UTC
In the notification view, there's a settings button that opens a modal. The "Save" button inside the modal doesn’t work in the desktop version of Safari (though it works fine on iOS). I’ve tested this on both my instance and the official vernissage.photos instance, and the issue is the same on both.

The button gives visual feedback when clicked, but nothing happens, and the notification settings are not saved.

**Comment by mgrzeca** [comment] 2024-10-06 12:07
I’ve checked the browser's JavaScript console, and there are no errors or messages displayed when the "Save" button is clicked.

**Comment by mczachurski** [comment] 2024-10-06 14:43
I cannot reproduce that issue. Check please if you have "Service worker" enabled in Safari:

<img width="948" alt="Screenshot 2024-10-06 at 16 31 51" src="https://github.com/user-attachments/assets/82ac04a8-6116-4df2-bc25-34620a73ea29">

Verify also if in the Safari console you switched to see all console messages:

<img width="601" alt="Screenshot 2024-10-06 at 16 39 43" src="https://github.com/user-attachments/assets/ea3e7732-de54-4103-8964-aa0b1ed9edbd">

Theoretically, you should not see the "Settings" button when the "Service worker" is disabled, but I don't have any other ideas.

**Comment by mgrzeca** [comment] 2024-10-06 15:46
Yes, I have service workers enabled, and the JavaScript console in Safari 18.0 is set to display all messages by default. I’ve also tried disabling Safari’s built-in content blockers and tested with AdGuard turned off, but the issue persists.

Let me know if there’s anything else I should check!

**Comment by mczachurski** [comment] 2024-10-06 17:05
I will add more messages during the process of saving notifications in the new version of the application, which might help us identify the issue. I’ll let you know once it’s done.

**Comment by mczachurski** [comment] 2024-10-07 09:08
Can you verify what error message do you have now?

And can you verify also what do you have in the Notifications tab in the Safari:

<img width="846" alt="Screenshot 2024-10-07 at 11 06 51" src="https://github.com/user-attachments/assets/1618e3e1-3393-409f-8de3-96b34bfcac17">

**Comment by mgrzeca** [comment] 2024-10-07 09:30
<img width="1440" alt="Zrzut ekranu 2024-10-7 o 11 28 31" src="https://github.com/user-attachments/assets/c96fecc5-366b-490f-87be-c3f922270130">

**Comment by mgrzeca** [comment] 2024-10-07 09:31
but for some reason, it works on iOS, and notifications are also working correctly for me on iPhone

**Comment by mgrzeca** [comment] 2024-10-07 09:35
I’m getting exactly the same message on the official instance.

**Comment by mczachurski** [comment] 2024-10-07 18:52
The code which is responsible for notification subscription looks like that:

```ts
const subscription = await this.swPushService.requestSubscription({
    serverPublicKey: this.settingsService.publicSettings.webPushVapidPublicKey
});

const jsonObject = subscription.toJSON();
this.endpoint = jsonObject.endpoint;
this.p256dh = jsonObject.keys?.p256dh;
this.auth = jsonObject.keys?.auth;

if (!this.endpoint || !this.p256dh || !this.auth) {
    this.messageService.showError('Error during generating encryption keys for Web push.');
    return;
}
```

Basically we have three steps here:
1. `requestSubscription` - after that operation you should have question from browser about notification approval,
2. `subscription.toJSON()` - then we have to ask for browser generated public keys,
3. `!this.endpoint || !this.p256dh || !this.auth` - check if everything has been retrieved from browser,

Seems like the first step is failing somehow (not returning correct `PushSubscription` object). But for now I don’t know why.

**Comment by mgrzeca** [comment] 2024-10-18 09:27
Has anything been fixed regarding the "Save" button in the notification settings? Today, the button is working for me on both my instance and the official one.

**Comment by mczachurski** [comment] 2024-11-30 08:34
No. I didn't do nothing regarding this. I think it was something with browser (cache or something like that). Can I close the issue?

**Closed** 2024-12-06 08:14 UTC
